#!/bin/bash
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt-get update
sudo apt-get install ansible -y
sudo apt-get install nginx -y
sudo apt-get install python3-apt -y
sudo apt-get install git -y
sudo apt-get install stress -y
sudo git clone https://github.com/Anji399/ansautoscaletest.git /myrepo
######USE aws-autoscaling branch for testing aws autoscaling##########################
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
sudo ansible-playbook /myrepo/playbook.yaml
